### ISSUE TITLE
can i set user to live-build system?

### ISSUE THREAD

**Issue by fengjian1993** [I-LeCorbeau/debian-live-build#4]
i have some preset user needs to be set to my live-build system, how can i do this?
and my preset program is java-based program. it started by systemd customed. these can be preset to live-build system too?
thanks ;)

**Comment by IanLeCorbeau** [comment]
You can use live-config to further customize the system: https://manpages.debian.org/unstable/live-config-doc/live-config.7.en.html#live~6

You can indeed start custom scripts/systemd units at boot. There may be another way of doing it, but simply creating a _0001-custom-service.hook.chroot_ script in config/hooks/normal/ and adding the _systemctl enable **service-name**_ in it would be the most straightforward way. 

You could also use a preseed file (https://wiki.debian.org/DebianInstaller/Preseed), but I've never done it so I can't really help in that regard.

**Comment by fengjian1993** [comment]
> You can use live-config to further customize the system: https://manpages.debian.org/unstable/live-config-doc/live-config.7.en.html#live~6
> 
> You can indeed start custom scripts/systemd units at boot. There may be another way of doing it, but simply creating a _0001-custom-service.hook.chroot_ script in config/hooks/normal/ and adding the _systemctl enable **service-name**_ in it would be the most straightforward way.
> 
> You could also use a preseed file (https://wiki.debian.org/DebianInstaller/Preseed), but I've never done it so I can't really help in that regard.

thanks for your reply ;) i tried preset my user by hook script useradd. seems ok ;)
and yes i will try to use systemd shell command

i use debian 11(bullseye) there are many folder under /config and confused me ;) 

another question, every time i changed config under /config. i need step by step lb clean -> lb config -> lb build? any solution can resolve it? it takes my so much time

**Comment by IanLeCorbeau** [comment]
Perhaps lb clean could be omitted, but the directory would end up eating quite a lot of space over time. A good way to speed things up would be to create a shell script to execute the commands in order.

**Comment by fengjian1993** [comment]
> Perhaps lb clean could be omitted, but the directory would end up eating quite a lot of space over time. A good way to speed things up would be to create a shell script to execute the commands in order.

yes but build takes too much time!
now i meet an issue,
i need add some new file to chroot directory and i dont want to do build again (takes to much time), so i just run lb binary --force. I noticed weird incident that even if no change to chroot, my live-image-amd64.hybrid.iso also bigger than before.

1437204480  8月 19 15:40 live-image-amd64.hybrid.iso
->
1469186048  8月 19 17:19 live-image-amd64.hybrid.iso

have you meet same issue before?

**Comment by IanLeCorbeau** [comment]
I have never used lb binary --force so I can't be of much help here. It's possible that by not running lb clean and lb build, some files get duplicated during the binary stage. The only way to avoid this kind of surprises and keep consistency across subsequent ISOs is to run lb clean, lb config and then lb build again.

Do you run lb clean standalone or do you add arguments to the command? lb clean without arguments will shorten overall build time.

**Comment by fengjian1993** [comment]
> I have never used lb binary --force so I can't be of much help here. It's possible that by not running lb clean and lb build, some files get duplicated during the binary stage. The only way to avoid this kind of surprises and keep consistency across subsequent ISOs is to run lb clean, lb config and then lb build again.
> 
> Do you run lb clean standalone or do you add arguments to the command? lb clean without arguments will shorten overall build time.

i run lb clean standalone.
other question i want discuss with you is how to decrease the size of the iso package? any experiences can share with me ;)

**Comment by IanLeCorbeau** [comment]
The size of the iso really depends on the software it includes. The installer alone can add up to 300mb to it (which is why I don't include it anymore and wrote a simple installer in bash). Avoiding the big DEs will also help, but even then, my iso only has dwm and is still a little over 900 mb in size!

**Comment by fengjian1993** [comment]
> The size of the iso really depends on the software it includes. The installer alone can add up to 300mb to it (which is why I don't include it anymore and wrote a simple installer in bash). Avoiding the big DEs will also help, but even then, my iso only has dwm and is still a little over 900 mb in size!

my iso 1.24gb now, and it contains opensearch, kafka ... and 5 java program. seems nothing can decrease it

**Comment by IanLeCorbeau** [comment]
Did you use the minbase variant? Another option is to set apt to not install recommended packages with by adding --apt-recommends false to the lb config command. Though that may require tracking down certain dependencies to add them to pkgs.list.chroot later on.

**Comment by fengjian1993** [comment]
> Did you use the minbase variant? Another option is to set apt to not install recommended packages with by adding --apt-recommends false to the lb config command. Though that may require tracking down certain dependencies to add them to pkgs.list.chroot later on.

many thanks about this.
happy to chat with you. ;)

**Comment by IanLeCorbeau** [comment]
You're welcome!
